console.log("Hello! I'm your coding fun fact guide!");
let botName = "Tony";
let botLocation ="New York";
let favoriteLanguage ="English";
console.log("My name is "+ botName +" and I live on "+botLocation+".");
console.log("My favorite programming language is "+favoriteLanguage+".");
let codingFact;
codingFact = "I can help you to code in " + favoriteLanguage;
console.log(codingFact);
codingFact = " I can speak in " +favoriteLanguage;
console.log(codingFact);
codingFact = "I dont know any other language other than "+favoriteLanguage;
console.log(codingFact);
console.log("It was fun sharing these facts with you. Goodbye! - " +botName+" from "+botLocation+".");
